# Generated by Django 2.1.5 on 2019-05-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190519_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
